"""add_financial_context_goals_mandates

Revision ID: 87cbaa8cd11a
Revises: m3n4o5p6q7r8
Create Date: 2026-09-29 18:04:27.403159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87cbaa8cd11a'
down_revision: Union[str, None] = 'm3n4o5p6q7r8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('financial_scope', sa.Enum('INDIVIDUAL', 'PERSONAL_SHARE_OF_HOUSEHOLD', name='financialscope'), nullable=False),
    sa.Column('planning_currency', sa.String(length=3), nullable=False),
    sa.Column('spending_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('monthly_net_income', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('income_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('income_stability', sa.Enum('PREDICTABLE', 'VARIABLE', 'AT_RISK', 'TEMPORARY', 'UNKNOWN', name='incomestability'), nullable=False),
    sa.Column('monthly_essential_expenses', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('monthly_discretionary_expenses', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('non_debt_obligations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependents_count', sa.Integer(), nullable=True),
    sa.Column('external_support', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage_declarations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reserve_self_report', sa.String(length=100), nullable=True),
    sa.Column('user_surplus_estimate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_financial_contexts_user_id', 'financial_contexts', ['user_id'], unique=False)
    op.create_table('financial_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal_type', sa.Enum('RETIREMENT', 'HOME_PURCHASE', 'EDUCATION', 'EMERGENCY_RESERVE', 'WEALTH_GROWTH', 'FINANCIAL_INDEPENDENCE', 'CAPITAL_PRESERVATION', 'INCOME_GENERATION', 'BUSINESS_CAPITAL', 'TRAVEL', 'OTHER', name='goaltype'), nullable=False),
    sa.Column('mode', sa.Enum('TARGET_AMOUNT', 'TARGET_INCOME', 'OPEN_ENDED', name='goalmode'), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('horizon_band', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Enum('ESSENTIAL', 'IMPORTANT', 'ASPIRATIONAL', name='goalpriority'), nullable=False),
    sa.Column('date_flexibility', sa.Enum('FIXED', 'LIMITED', 'FLEXIBLE', 'UNKNOWN', name='flexibility'), nullable=False),
    sa.Column('amount_flexibility', sa.Enum('FIXED', 'LIMITED', 'FLEXIBLE', 'UNKNOWN', name='amount_flexibility_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ACHIEVED', 'CANCELLED', 'ARCHIVED', name='goalstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_financial_goals_status', 'financial_goals', ['status'], unique=False)
    op.create_index('ix_financial_goals_user_id', 'financial_goals', ['user_id'], unique=False)
    op.create_table('investment_mandates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mandate_type', sa.Enum('RESERVE', 'PRESERVATION', 'INCOME', 'GROWTH', 'SPECULATIVE', 'CUSTOM', name='mandatetype'), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('horizon_override', sa.String(length=50), nullable=True),
    sa.Column('risk_capacity', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='riskcapacity'), nullable=True),
    sa.Column('target_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concentration_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', name='mandatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investment_mandates_goal_id', 'investment_mandates', ['goal_id'], unique=False)
    op.create_index('ix_investment_mandates_user_id', 'investment_mandates', ['user_id'], unique=False)
    op.create_table('capital_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mandate_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('ASSET', 'CASH_ACCOUNT', name='resourceassignmenttype'), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('cash_account_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('assigned_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandate_id'], ['investment_mandates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capital_assignments_asset_id', 'capital_assignments', ['asset_id'], unique=False)
    op.create_index('ix_capital_assignments_cash_account_id', 'capital_assignments', ['cash_account_id'], unique=False)
    op.create_index('ix_capital_assignments_mandate_id', 'capital_assignments', ['mandate_id'], unique=False)
    op.create_index('ix_capital_assignments_user_id', 'capital_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_capital_assignments_user_id', table_name='capital_assignments')
    op.drop_index('ix_capital_assignments_mandate_id', table_name='capital_assignments')
    op.drop_index('ix_capital_assignments_cash_account_id', table_name='capital_assignments')
    op.drop_index('ix_capital_assignments_asset_id', table_name='capital_assignments')
    op.drop_table('capital_assignments')
    op.drop_index('ix_investment_mandates_user_id', table_name='investment_mandates')
    op.drop_index('ix_investment_mandates_goal_id', table_name='investment_mandates')
    op.drop_table('investment_mandates')
    op.drop_index('ix_financial_goals_user_id', table_name='financial_goals')
    op.drop_index('ix_financial_goals_status', table_name='financial_goals')
    op.drop_table('financial_goals')
    op.drop_index('ix_financial_contexts_user_id', table_name='financial_contexts')
    op.drop_table('financial_contexts')

    # PostgreSQL ENUMs outlive their tables. Drop this revision's owned types
    # only after every referencing table has gone, so re-upgrade can recreate
    # them. Do not use CASCADE: unexpected external dependencies must fail
    # transactionally instead of silently deleting other schema objects.
    for enum_name in (
        'resourceassignmenttype',
        'mandatestatus',
        'riskcapacity',
        'mandatetype',
        'goalstatus',
        'amount_flexibility_enum',
        'flexibility',
        'goalpriority',
        'goalmode',
        'goaltype',
        'incomestability',
        'financialscope',
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

