"""create assets table

Revision ID: d63f1a120486
Revises: 4f0bac35b3a9
Create Date: 2026-03-27 21:38:50.931280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63f1a120486'
down_revision: Union[str, None] = '4f0bac35b3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'FOREX', 'GOLD', 'CRYPTO', 'FUND', 'REAL_ESTATE', 'CUSTOM', name='assettype', native_enum=False, length=20), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('purchase_currency', sa.String(length=3), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_price_currency', sa.String(length=3), nullable=True),
    sa.Column('is_manual_price', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=False)
    op.create_index('ix_assets_user_id', 'assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_user_id', table_name='assets')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.drop_index('ix_assets_asset_type', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
